const cardRoutes = {
  poker: {
    clubs: [
      require("../assets/images/PNG-cards-1.3/ace_of_clubs.png"),
      require("../assets/images/PNG-cards-1.3/2_of_clubs.png"),
      require("../assets/images/PNG-cards-1.3/3_of_clubs.png"),
      require("../assets/images/PNG-cards-1.3/4_of_clubs.png"),
      require("../assets/images/PNG-cards-1.3/5_of_clubs.png"),
      require("../assets/images/PNG-cards-1.3/6_of_clubs.png"),
      require("../assets/images/PNG-cards-1.3/7_of_clubs.png"),
      require("../assets/images/PNG-cards-1.3/8_of_clubs.png"),
      require("../assets/images/PNG-cards-1.3/9_of_clubs.png"),
      require("../assets/images/PNG-cards-1.3/10_of_clubs.png"),
      require("../assets/images/PNG-cards-1.3/jack_of_clubs2.png"),
      require("../assets/images/PNG-cards-1.3/queen_of_clubs2.png"),
      require("../assets/images/PNG-cards-1.3/king_of_clubs2.png"),
    ],
    diamonds: [
      require("../assets/images/PNG-cards-1.3/ace_of_diamonds.png"),
      require("../assets/images/PNG-cards-1.3/2_of_diamonds.png"),
      require("../assets/images/PNG-cards-1.3/3_of_diamonds.png"),
      require("../assets/images/PNG-cards-1.3/4_of_diamonds.png"),
      require("../assets/images/PNG-cards-1.3/5_of_diamonds.png"),
      require("../assets/images/PNG-cards-1.3/6_of_diamonds.png"),
      require("../assets/images/PNG-cards-1.3/7_of_diamonds.png"),
      require("../assets/images/PNG-cards-1.3/8_of_diamonds.png"),
      require("../assets/images/PNG-cards-1.3/9_of_diamonds.png"),
      require("../assets/images/PNG-cards-1.3/10_of_diamonds.png"),
      require("../assets/images/PNG-cards-1.3/jack_of_diamonds2.png"),
      require("../assets/images/PNG-cards-1.3/queen_of_diamonds2.png"),
      require("../assets/images/PNG-cards-1.3/king_of_diamonds2.png"),
    ],
    hearts: [
      require("../assets/images/PNG-cards-1.3/ace_of_hearts.png"),
      require("../assets/images/PNG-cards-1.3/2_of_hearts.png"),
      require("../assets/images/PNG-cards-1.3/3_of_hearts.png"),
      require("../assets/images/PNG-cards-1.3/4_of_hearts.png"),
      require("../assets/images/PNG-cards-1.3/5_of_hearts.png"),
      require("../assets/images/PNG-cards-1.3/6_of_hearts.png"),
      require("../assets/images/PNG-cards-1.3/7_of_hearts.png"),
      require("../assets/images/PNG-cards-1.3/8_of_hearts.png"),
      require("../assets/images/PNG-cards-1.3/9_of_hearts.png"),
      require("../assets/images/PNG-cards-1.3/10_of_hearts.png"),
      require("../assets/images/PNG-cards-1.3/jack_of_hearts2.png"),
      require("../assets/images/PNG-cards-1.3/queen_of_hearts2.png"),
      require("../assets/images/PNG-cards-1.3/king_of_hearts2.png"),
    ],
    spades: [
      require("../assets/images/PNG-cards-1.3/ace_of_spades.png"),
      require("../assets/images/PNG-cards-1.3/2_of_spades.png"),
      require("../assets/images/PNG-cards-1.3/3_of_spades.png"),
      require("../assets/images/PNG-cards-1.3/4_of_spades.png"),
      require("../assets/images/PNG-cards-1.3/5_of_spades.png"),
      require("../assets/images/PNG-cards-1.3/6_of_spades.png"),
      require("../assets/images/PNG-cards-1.3/7_of_spades.png"),
      require("../assets/images/PNG-cards-1.3/8_of_spades.png"),
      require("../assets/images/PNG-cards-1.3/9_of_spades.png"),
      require("../assets/images/PNG-cards-1.3/10_of_spades.png"),
      require("../assets/images/PNG-cards-1.3/jack_of_spades2.png"),
      require("../assets/images/PNG-cards-1.3/queen_of_spades2.png"),
      require("../assets/images/PNG-cards-1.3/king_of_spades2.png"),
    ],
  },
  espanyola: {
    oros: [
      require("../assets/images/cartes_baralla_espanyola/oros_01.png"),
      require("../assets/images/cartes_baralla_espanyola/oros_02.png"),
      require("../assets/images/cartes_baralla_espanyola/oros_03.png"),
      require("../assets/images/cartes_baralla_espanyola/oros_04.png"),
      require("../assets/images/cartes_baralla_espanyola/oros_05.png"),
      require("../assets/images/cartes_baralla_espanyola/oros_06.png"),
      require("../assets/images/cartes_baralla_espanyola/oros_07.png"),
      require("../assets/images/cartes_baralla_espanyola/oros_08.png"),
      require("../assets/images/cartes_baralla_espanyola/oros_09.png"),
      require("../assets/images/cartes_baralla_espanyola/oros_10.png"),
      require("../assets/images/cartes_baralla_espanyola/oros_11.png"),
      require("../assets/images/cartes_baralla_espanyola/oros_12.png"),
    ],
    copes: [
      require("../assets/images/cartes_baralla_espanyola/copas_01.png"),
      require("../assets/images/cartes_baralla_espanyola/copas_02.png"),
      require("../assets/images/cartes_baralla_espanyola/copas_03.png"),
      require("../assets/images/cartes_baralla_espanyola/copas_04.png"),
      require("../assets/images/cartes_baralla_espanyola/copas_05.png"),
      require("../assets/images/cartes_baralla_espanyola/copas_06.png"),
      require("../assets/images/cartes_baralla_espanyola/copas_07.png"),
      require("../assets/images/cartes_baralla_espanyola/copas_08.png"),
      require("../assets/images/cartes_baralla_espanyola/copas_09.png"),
      require("../assets/images/cartes_baralla_espanyola/copas_10.png"),
      require("../assets/images/cartes_baralla_espanyola/copas_11.png"),
      require("../assets/images/cartes_baralla_espanyola/copas_12.png"),
    ],
    espases: [
      require("../assets/images/cartes_baralla_espanyola/espadas_01.png"),
      require("../assets/images/cartes_baralla_espanyola/espadas_02.png"),
      require("../assets/images/cartes_baralla_espanyola/espadas_03.png"),
      require("../assets/images/cartes_baralla_espanyola/espadas_04.png"),
      require("../assets/images/cartes_baralla_espanyola/espadas_05.png"),
      require("../assets/images/cartes_baralla_espanyola/espadas_06.png"),
      require("../assets/images/cartes_baralla_espanyola/espadas_07.png"),
      require("../assets/images/cartes_baralla_espanyola/espadas_08.png"),
      require("../assets/images/cartes_baralla_espanyola/espadas_09.png"),
      require("../assets/images/cartes_baralla_espanyola/espadas_10.png"),
      require("../assets/images/cartes_baralla_espanyola/espadas_11.png"),
      require("../assets/images/cartes_baralla_espanyola/espadas_12.png"),
    ],
    bastos: [
      require("../assets/images/cartes_baralla_espanyola/bastos_01.png"),
      require("../assets/images/cartes_baralla_espanyola/bastos_02.png"),
      require("../assets/images/cartes_baralla_espanyola/bastos_03.png"),
      require("../assets/images/cartes_baralla_espanyola/bastos_04.png"),
      require("../assets/images/cartes_baralla_espanyola/bastos_05.png"),
      require("../assets/images/cartes_baralla_espanyola/bastos_06.png"),
      require("../assets/images/cartes_baralla_espanyola/bastos_07.png"),
      require("../assets/images/cartes_baralla_espanyola/bastos_08.png"),
      require("../assets/images/cartes_baralla_espanyola/bastos_09.png"),
      require("../assets/images/cartes_baralla_espanyola/bastos_10.png"),
      require("../assets/images/cartes_baralla_espanyola/bastos_11.png"),
      require("../assets/images/cartes_baralla_espanyola/bastos_12.png"),
    ],
  },
};

export default cardRoutes;
